image: alpine/latest
packages:
  - rsync
  - go
sources:
  - https://git.sr.ht/~sircmpwn/drewdevault.com
  - https://git.sr.ht/~sircmpwn/hugo
secrets:
  - 160a72cf-34d6-47b7-928b-c13b42b4d4f6
tasks:
- openring: |
    cd drewdevault.com
    curl -O https://yukari.sr.ht/openring
    chmod +x openring
    ./openring \
      -s https://emersion.fr/blog/rss.xml \
      -s http://way-cooler.org/feed.xml \
      -s https://danluu.com/atom.xml \
      -s https://os.phil-opp.com/rss.xml \
      -s https://blog.golang.org/feed.atom \
      -s https://aphyr.com/posts.atom \
      -s https://sourcehut.org/blog/index.xml \
      -s https://100r.co/links/rss.xml \
      -s https://tonsky.me/blog/atom.xml \
      < layouts/partials/webring-in.template \
      > layouts/partials/webring-out.html
- hugo: |
    cd hugo
    go build --tags extended
    sudo cp hugo /usr/local/bin/
- build: |
    cd drewdevault.com
    /usr/local/bin/hugo
- upload: |
    cd drewdevault.com
    echo "StrictHostKeyChecking=no" >> ~/.ssh/config
    rsync -rP public/ deploy@drewdevault.com:/var/www/drewdevault.com/
