image: alpine/edge
packages:
  - go
  - hugo
  - hut
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~sircmpwn/drewdevault.com
  - https://git.sr.ht/~sircmpwn/openring
triggers:
  - action: email
    condition: always
    to: Drew DeVault <sir@cmpwn.com>
tasks:
- openring: |
    cd openring
    go build -o openring
    sudo cp openring /usr/local/bin/
- build: |
    cd drewdevault.com
    /usr/local/bin/openring \
      -s https://emersion.fr/blog/rss.xml \
      -s http://way-cooler.org/feed.xml \
      -s https://os.phil-opp.com/rss.xml \
      -s https://blog.golang.org/feed.atom \
      -s https://aphyr.com/posts.atom \
      -s https://sourcehut.org/blog/index.xml \
      -s https://100r.co/links/rss.xml \
      -s https://www.bitsaboutmoney.com/archive/rss/ \
      -s https://blog.brixit.nl/rss/ \
      -s https://brr.fyi/feed.xml \
      -s https://bitfehler.srht.site/index.xml \
      -s https://adnano.co/atom.xml \
      -s https://www.willowbarraco.fr:443/atom.xml \
      -s https://torresjrjr.com/archive/index.xml \
      < webring-in.template \
      > layouts/partials/webring-out.html
    hugo
- upload: |
    cd drewdevault.com
    hut pages publish -d drewdevault.com ./public/
