image: alpine/latest
packages:
  - rsync
  - go
sources:
  - https://git.sr.ht/~sircmpwn/drewdevault.com
  - https://git.sr.ht/~sircmpwn/hugo
  - https://git.sr.ht/~sircmpwn/openring
secrets:
  - 160a72cf-34d6-47b7-928b-c13b42b4d4f6
triggers:
  - action: email
    condition: always
    to: Drew DeVault <sir@cmpwn.com>
tasks:
- openring: |
    cd openring
    go build -o openring
    sudo cp openring /usr/local/bin/
- hugo: |
    cd hugo
    go build --tags extended
    sudo cp hugo /usr/local/bin/
- build: |
    cd drewdevault.com
    /usr/local/bin/openring \
      -s https://emersion.fr/blog/rss.xml \
      -s http://way-cooler.org/feed.xml \
      -s https://danluu.com/atom.xml \
      -s https://os.phil-opp.com/rss.xml \
      -s https://blog.golang.org/feed.atom \
      -s https://aphyr.com/posts.atom \
      -s https://sourcehut.org/blog/index.xml \
      -s https://100r.co/links/rss.xml \
      -s https://tonsky.me/blog/atom.xml \
      < webring-in.template \
      > layouts/partials/webring-out.html
    /usr/local/bin/hugo
- upload: |
    cd drewdevault.com
    echo "StrictHostKeyChecking=no" >> ~/.ssh/config
    rsync -rP public/ deploy@drewdevault.com:/var/www/drewdevault.com/
    rsync -rP public/gemini/ deploy@drewdevault.com:/srv/gemini/drewdevault.com/
