name: Test CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
      - run: nix build
      - name: Dummy deploy (e.g. copy to s3, gh pages publish)
        run: ls -R result
